server:
  port: 8091
  servlet:
    context-path: /api/public-info
management:
  server:
    port: 8190
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=public_info
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public_info

  liquibase:
      enabled: false

  application:
    name: public-info-app